apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem # Not needed.
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Not needed.
  hostPath:
    path: /home/abhay/mysqldata        #This is your host path where your data will be stored. This will get created automatically as per the mentined path, when we will run "mysql-deployment.yml".
